### ISSUE TITLE
java.util.zip.ZipException: Not in GZIP format

### ISSUE THREAD

**Issue by KadTheHunter** [mircokroon/minecraft-maps-to-images#1]
```
java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
        at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
        at Main.gzipDecompress(Main.java:95)
        at Main.read(Main.java:86)
        at Main.main(Main.java:40)
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at Main.main(Main.java:45)
```

I get this error when trying to convert one of my maps. Only this one so far, no others.
If I keep running map-to-img it eventually converts it, but with insanely screwed up colors.

The .dat File:
https://gofile.io/d/vlq89D
(GitHub really won't let me upload it? smh)

Below is a screenshot of the actual map:
![2023-04-23_22 30 01](https://user-images.githubusercontent.com/47439649/233886378-f1ca6943-36e3-4761-8741-c7bd7d89686f.png)
and now what Map-to-Img will eventually spit out when it doesn't error:
![map_162137](https://user-images.githubusercontent.com/47439649/233886449-77420331-79af-4593-9257-2d9208c3a6a8.png)

**Comment by KadTheHunter** [comment]
According to another user, its likely that the GZIP error was caused by an overwritten or corrupted .dat file, and the colors being off was fixed in #2.
